##############################
# anvi-ncbi-cogs submit
##############################

universe = vanilla
executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/anvi-ncbi-cogs-annotate.sh

request_cpus = 12
request_memory = 20GB
arguments = $(contigs)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_anvi-ncbi.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_anvi-ncbi.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_anvi-ncbi.log

queue contigs from /home/GLBRCORG/emcdaniel/EBPR/AcDiv/metadata/Accumulibacter-anvio-contig-dbs.txt