##############################
# Danish WWTPs inStrain Queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/Danish-WWTPs-inStrain-queue.sh

request_cpus = 6
request_memory = 150GB
arguments = $(mapping) $(genome)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_inStrain_WWTPs.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_inStrain_WWTPs.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_inStrain_WWTPs.log

queue mapping,genome from metadata/Danish-WWTPs-inStrain-queues.txt