##############################
# Pairwise BLAST PID Queue
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/pairwise-BLAST-PID.sh

request_cpus = 4
request_memory = 10GB
arguments = $(group)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_BLAST_PID.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_BLAST_PID.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_BLAST_PID.log

queue group from metadata/core90-groups.txt