##############################
# R1R2 Bowtie Mapping Queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/R1R2-bowtie-mapping-queues.sh

request_cpus = 6
request_memory = 200GB
arguments = $(fastq) $(ref)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_bowtie2mapping.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_bowtie2mapping.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_bowtie2mapping.log

queue fastq,ref from metadata/R1R2-Acc-IA-IIA-mapping-queues.txt
