##############################
# R3R4 Bowtie Mapping Queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/R3R4_all_mapping.sh

request_cpus = 4
request_memory = 50GB
arguments = $(fastq) $(ref)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_bowtie2mapping.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_bowtie2mapping.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_bowtie2mapping.log

queue fastq,ref from metadata/R3R4-all-metaGs-mapping-queue.txt
