##############################
# R3R4 inStrain Queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/R3R4-inStrain-queue.sh

request_cpus = 4
request_memory = 50GB
arguments = $(mapping) $(genome) $(reactor) $(scaffolds)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_inStrain.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_inStrain.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_inStrain.log

queue mapping,genome,reactor,scaffolds from metadata/R3R4-inStrain-queue.txt