##############################
# R3R4 all Combined inStrain Queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/R3R4-all-inStrain-queue.sh

request_cpus = 4
request_memory = 150GB
arguments = $(mapping) $(genome) $(scaffolds)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_inStrain.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_inStrain.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_inStrain.log

queue mapping,genome,scaffolds from metadata/R3R4-all-inStrain-queue.txt