##############################
# R1R2 Samtools Queues
##############################

executable = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/executables/WWTPs-samtools-queues.sh

request_cpus = 6
request_memory = 200GB
arguments = $(file)

output = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/outs/$(Cluster)_$(Process)_samtools.out
error = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/errs/$(Cluster)_$(Process)_samtools.err
log = /home/GLBRCORG/emcdaniel/EBPR/AcDiv/logs/$(Cluster)_$(Process)_samtools.log

queue file from metadata/WWTPs-samtools-queues.txt
