library(tidyverse)
library(viridis)

ani_results <- read_tsv("results/ANI/acPhy_ANI.txt", col_names = FALSE)

colnames(ani_results) <- c("genome1", "genome2", "ANI", "x1", "x2")
acc_ani <- ani_results %>% 
  select(genome1, genome2, ANI)

acc_ani$genome1 <- gsub(".fna", "", acc_ani$genome1)
acc_ani$genome2 <- gsub(".fna", "", acc_ani$genome2)

order <- c('GCA_000585055.1',
           'GCA_000987445.1',
           'GCA_003332265.1',
           'Delftensis',
           'GCA_012939955.1',
           'GCA_000585075.1',
           'GCA_009467855.1',
           'UW3',
           'UW4',
           'UW8-POB',
           'GCA_900089955.1',
           'GCA_000024165.1',
           'UW5',
           'UW9-POB',
           'Hade_18-Q3-R52-61_BATAC.726',
           'OdNE_18-Q3-R46-58_BAT3C.415',
           'Fred_18-Q3-R57-64_MAXAC.027',
           'UW10-POB',
           'GCA_012940005.1',
           'GCA_000584955.2',
           'GCA_005889575.1',
           'GCA_000987395.1',
           'GCA_000584975.2',
           'GCA_013414765.1',
           'UW11-POB',
           'UW6',
           'Fred_18-Q3-R57-64_BAT3C.720',
           'EsbW_18-Q3-R4-48_BATAC.285',
           'UW12-POB',
           'GCA_002345025.1',
           'GCA_000585015.1',
           'GCA_005524045.1',
           'GCA_013347225.1',
           'UW13-POB',
           'UW7')

acc_ani$genome1 <- factor(acc_ani$genome1, levels=c(order))
acc_ani$genome2 <- factor(acc_ani$genome2, levels=c(order))

ani_figure <- acc_ani %>% ggplot(aes(x=genome1, y=genome2, fill=ANI)) + geom_raster() + scale_fill_viridis(option = "magma") + scale_x_discrete(labels=c('BA-92',
                                                                                                                                           'HKU1',
                                                                                                                                           'UW-LDO',
                                                                                                                                           'DELFT',
                                                                                                                                           'SBR_S',
                                                                                                                                           'BA-93',
                                                                                                                                           'CANDO_1',
                                                                                                                                           'UW3',
                                                                                                                                           'UW4',
                                                                                                                                           'UW8-POB',
                                                                                                                                           'AALB',
                                                                                                                                           'UW1',
                                                                                                                                           'UW5',
                                                                                                                                           'UW9-POB',
                                                                                                                                           'Hade_18-Q3-R52-61_BATAC.726',
                                                                                                                                           'OdNE_18-Q3-R46-58_BAT3C.415',
                                                                                                                                           'Fred_18-Q3-R57-64_MAXAC.027',
                                                                                                                                           'UW10-POB',
                                                                                                                                           'SBR_L',
                                                                                                                                           'SK-01',
                                                                                                                                           'BIN19',
                                                                                                                                           'HKU2',
                                                                                                                                           'SK-02',
                                                                                                                                           'SSA1',
                                                                                                                                           'UW11-POB',
                                                                                                                                           'UW6',
                                                                                                                                           'Fred_18-Q3-R57-64_BAT3C.720',
                                                                                                                                           'EsbW_18-Q3-R4-48_BATAC.285',
                                                                                                                                           'UW12-POB',
                                                                                                                                           'UBA2327',
                                                                                                                                           'SK-12',
                                                                                                                                           'SCELSE-1',
                                                                                                                                           'SSB1',
                                                                                                                                           'UW13-POB',
                                                                                                                                           'UW7')) + scale_y_discrete(labels=c('BA-92',
                                                                                                                                                                               'HKU1',
                                                                                                                                                                               'UW-LDO',
                                                                                                                                                                               'DELFT',
                                                                                                                                                                               'SBR_S',
                                                                                                                                                                               'BA-93',
                                                                                                                                                                               'CANDO_1',
                                                                                                                                                                               'UW3',
                                                                                                                                                                               'UW4',
                                                                                                                                                                               'UW8-POB',
                                                                                                                                                                               'AALB',
                                                                                                                                                                               'UW1',
                                                                                                                                                                               'UW5',
                                                                                                                                                                               'UW9-POB',
                                                                                                                                                                               'Hade_18-Q3-R52-61_BATAC.726',
                                                                                                                                                                               'OdNE_18-Q3-R46-58_BAT3C.415',
                                                                                                                                                                               'Fred_18-Q3-R57-64_MAXAC.027',
                                                                                                                                                                               'UW10-POB',
                                                                                                                                                                               'SBR_L',
                                                                                                                                                                               'SK-01',
                                                                                                                                                                               'BIN19',
                                                                                                                                                                               'HKU2',
                                                                                                                                                                               'SK-02',
                                                                                                                                                                               'SSA1',
                                                                                                                                                                               'UW11-POB',
                                                                                                                                                                               'UW6',
                                                                                                                                                                               'Fred_18-Q3-R57-64_BAT3C.720',
                                                                                                                                                                               'EsbW_18-Q3-R4-48_BATAC.285',
                                                                                                                                                                               'UW12-POB',
                                                                                                                                                                               'UBA2327',
                                                                                                                                                                               'SK-12',
                                                                                                                                                                               'SCELSE-1',
                                                                                                                                                                               'SSB1',
                                                                                                                                                                               'UW13-POB',
                                                                                                                                                                               'UW7')) + theme(axis.title.x=element_blank(), axis.title.y=element_blank()) + theme(axis.text.x= element_text(angle=85, hjust=1))

ggsave("figures/AcPhy-ANI.png", ani_figure, width=20, height=16, units=c("cm"))
